version: 2.1
orbs:
  node: circleci/node@1.1

jobs:
  integration-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          cache-version: v4
          cache-key: package-lock.json
          use-strict-cache: true
          steps:
            - run: npm ci
            - run: npm run test # run our integration tests
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          cache-version: v4
          cache-key: package-lock.json
          use-strict-cache: true
          steps:
            - run: npx sls deploy --verbose

  acceptance-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          cache-version: v4
          cache-key: package-lock.json
          use-strict-cache: true
          steps:
            - run: npm ci
            - run: npm run acceptance

workflows:
  version: 2
  dev:
    jobs:
      - deploy
      - integration-test:
          requires:
            - deploy
      - acceptance-test:
          requires:
            - integration-test